version: "3"
services:
  laravel:
    build: .
    tty: true
    volumes:
      - .:/var/www/laravel
    working_dir: /var/www/laravel
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_todo
    volumes:
      - ./db:/var/lib/mysql
